const FILESYSTEM_ATTRIBUTE_LABELS: Record<string, string> = {
  'نام فضا': 'نام فضا',
  pool: 'نام Pool',
  Pool: 'نام Pool',
  mountpoint: 'نقطه اتصال',
  available: 'فضای در دسترس',
  compressratio: 'نسبت فشرده‌سازی',
  createtxg: 'TXG ایجاد',
  creation: 'تاریخ ایجاد',
  encryptionroot: 'ریشه رمزگذاری',
  filesystem_count: 'تعداد فایل‌سیستم',
  guid: 'شناسه GUID',
  inconsistent: 'ناسازگار',
  ivsetguid: 'شناسه مجموعه IV',
  keyguid: 'شناسه کلید',
  keystatus: 'وضعیت کلید',
  logicalreferenced: 'حجم منطقی ارجاع‌شده',
  logicalused: 'حجم منطقی مصرف‌شده',
  mounted: 'مونت شده',
  name: 'نام',
  objsetid: 'شناسه Object Set',
  origin: 'منبع',
  prevsnap: 'اسنپ‌شات قبلی',
  receive_resume_token: 'توکن ادامه دریافت',
  redact_snaps: 'اسنپ‌شات‌های بازنویسی‌شده',
  redacted: 'بازنویسی شده',
  refcompressratio: 'نسبت فشرده‌سازی مرجع',
  referenced: 'فضای ارجاع‌شده',
  remaptxg: 'TXG بازنگاشت',
  snapshot_count: 'تعداد اسنپ‌شات',
  type: 'نوع',
  unique: 'حجم یکتا',
  used: 'فضای استفاده‌شده',
  usedbychildren: 'استفاده‌شده توسط فرزندان',
  usedbydataset: 'استفاده‌شده توسط دیتاست',
  usedbyrefreservation: 'استفاده‌شده توسط رزرو مرجع',
  usedbysnapshots: 'استفاده‌شده توسط اسنپ‌شات‌ها',
  useraccounting: 'حسابداری کاربر',
  written: 'حجم نوشته‌شده',
  aclinherit: 'ارث‌بری ACL',
  aclmode: 'حالت ACL',
  acltype: 'نوع ACL',
  atime: 'زمان دسترسی',
  canmount: 'قابل مونت',
  casesensitivity: 'حساسیت به حروف',
  checksum: 'بررسی صحت',
  compression: 'فشرده‌سازی',
  context: 'متن امنیتی',
  copies: 'تعداد کپی',
  dedup: 'حذف داده تکراری',
  defcontext: 'متن پیش‌فرض',
  devices: 'دستگاه‌ها',
  dnodesize: 'اندازه Dnode',
  encryption: 'رمزگذاری',
  exec: 'اجرا',
  filesystem_limit: 'محدودیت فایل‌سیستم',
  fscontext: 'متن فایل‌سیستم',
  keyformat: 'فرمت کلید',
  keylocation: 'محل کلید',
  logbias: 'اولویت لاگ',
  mlslabel: 'برچسب MLS',
  nbmand: 'NBMAND',
  normalization: 'نرمال‌سازی',
  overlay: 'Overlay',
  pbkdf2iters: 'تعداد تکرار PBKDF2',
  pbkdf2salt: 'نمک PBKDF2',
  primarycache: 'کش اصلی',
  quota: 'سهمیه',
  readonly: 'فقط‌خواندنی',
  recordsize: 'اندازه رکورد',
  redundant_metadata: 'متادیتای افزونه',
  refquota: 'سهمیه مرجع',
  refreservation: 'رزرو مرجع',
  relatime: 'زمان نسبی',
  reservation: 'رزرو',
  rootcontext: 'متن ریشه',
  secondarycache: 'کش ثانویه',
  setuid: 'Setuid',
  sharenfs: 'اشتراک NFS',
  sharesmb: 'اشتراک SMB',
  snapdev: 'دستگاه اسنپ',
  snapdir: 'پوشه اسنپ',
  snapshot_limit: 'محدودیت اسنپ‌شات',
  special_small_blocks: 'بلاک‌های کوچک ویژه',
  sync: 'همگام‌سازی',
  utf8only: 'فقط UTF-8',
  version: 'نسخه',
  volmode: 'حالت Volume',
  vscan: 'وی‌اسکن',
  xattr: 'ویژگی‌های توسعه‌یافته',
  zoned: 'Zone بندی',
};

export const resolveFilesystemAttributeLabel = (key: string) => {
  const normalizedKey = key.trim();
  const lowerKey = normalizedKey.toLowerCase();

  return (
    FILESYSTEM_ATTRIBUTE_LABELS[normalizedKey] ??
    FILESYSTEM_ATTRIBUTE_LABELS[lowerKey] ??
    normalizedKey
  );
};

export default FILESYSTEM_ATTRIBUTE_LABELS;
